#! /bin/bash
###############################################
##
##  Copyright (2020, ) Institute of Software
##      Chinese Academy of Sciences
##          wuheng@iscas.ac.cn
##
###############################################


VERSION="1.3"

# Required
kube_pod_subnet="10.244.0.0/16"
kube_version="1.22.0"
kube_image_server="registry.cn-hangzhou.aliyuncs.com/google_containers"

## version
kube_backend_version="2.0.1"

# Optional
#fip="119.8.188.235:6443"
fip=""

# Kubernetes >= 1.22, only support containerd
#cnt_type="containerd"
cnt_type="docker"

# Deprecated
# docker_version="20.10.6"

openstack="victoria"

###########################################################
##
##  init-env
##
##########################################################

function disable-centos-security()
{
  sed -ie 's/SELINUX=permissive/SELINUX=disabled/g' /etc/selinux/config
  sed -ie 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
  systemctl stop firewalld
  systemctl disable firewalld
}

function disable-ubuntu-security()
{
  sudo ufw disable
}

function add-yum-repository()
{
  echo -e "[docker-ce-stable]\nname=Docker CE Stable - \$basearch \nbaseurl=https://download.docker.com/linux/centos/\$releasever/\$basearch/stable\nenabled=1 \ngpgcheck=1 \ngpgkey=https://download.docker.com/linux/centos/gpg" > /etc/yum.repos.d/docker-ce.repo
  echo -e "[kubernetes] \nname=Kubernetes - \$basearch \nbaseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-\$basearch/ \nenabled=1 \ngpgcheck=0 \nrepo_gpgcheck=0 \ngpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg" > /etc/yum.repos.d/kubernetes.repo
}


function add-apt-repository()
{
  arch=""
  if [[ $(arch) == "x86_64" ]]
  then
    arch="amd64"
  elif [[ $(arch) == "aarch64" ]]
  then
    arch="arm64"
  else
    echo "only support x86_64(amd64) and aarch64(arm64)"
    exit 1
  fi

  apt-get install apt-transport-https ca-certificates curl gnupg lsb-release lrzsz -y

  rm -rf /usr/share/keyrings/docker-archive-keyring.gpg
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo  "deb [arch=$arch signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  rm -rf /usr/share/keyrings/kubernetes-archive-keyring.gpg
  curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
  echo  "deb [arch=$arch signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
}

function yum-docker-k8s()
{
  #yum install -y wget docker-ce-${docker_version} kubectl-${kube_version} kubelet-${kube_version} kubeadm-${kube_version}
  yum install -y wget docker-ce kubectl-${kube_version} kubelet-${kube_version} kubeadm-${kube_version}

  ## kubernetes >= 1.22 only supports systemd
  echo "{" > /etc/docker/daemon.json
  echo "  \"exec-opts\": [\"native.cgroupdriver=systemd\"]" >> /etc/docker/daemon.json
  echo "}" >> /etc/docker/daemon.json
  systemctl daemon-reload

  systemctl start docker
  systemctl enable docker
  systemctl enable kubelet
}

function apt-docker-k8s()
{
  #dVer=$(apt-cache madison docker-ce | grep $docker_version | awk -F"|" '{print$2}' | sed 's/ //g')
  kVer=$(apt-cache madison kubelet | grep $kube_version | awk -F"|" '{print$2}' | sed 's/ //g')
  apt-get update
  #apt-get install docker-ce=$dVer kubectl=$kVer kubelet=$kVer kubeadm=$kVer
  apt-get install docker-ce kubectl=$kVer kubelet=$kVer kubeadm=$kVer
  systemctl start docker
  systemctl enable docker
  systemctl enable kubelet
}

function yum-containerd-k8s()
{

  yum install -y wget containerd.io kubectl-${kube_version} kubelet-${kube_version} kubeadm-${kube_version}
  
  echo "overlay" > /etc/modules-load.d/containerd.conf
  echo "br_netfilter" >> /etc/modules-load.d/containerd.conf

  modprobe overlay
  modprobe br_netfilter

  echo "net.bridge.bridge-nf-call-iptables  = 1" > /etc/sysctl.d/99-kubernetes-cri.conf
  echo "net.ipv4.ip_forward                 = 1" >> /etc/sysctl.d/99-kubernetes-cri.conf
  echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/99-kubernetes-cri.conf

  sysctl --system

  containerd config default > /etc/containerd/config.toml
  sed -i 's/k8s.gcr.io\/pause:3.2/registry.cn-hangzhou.aliyuncs.com\/google_containers\/pause:3.2/g' /etc/containerd/config.toml

  systemctl start containerd
  systemctl enable containerd

  echo "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd" > /etc/default/kubelet

  systemctl enable kubelet
}

function apt-containerd-k8s()
{

  kVer=$(apt-cache madison kubelet | grep $kube_version | awk -F"|" '{print$2}' | sed 's/ //g')
  apt-get update
  apt-get install containerd.io kubectl=$kVer kubelet=$kVer kubeadm=$kVer
  
  echo "overlay" > /etc/modules-load.d/containerd.conf
  echo "br_netfilter" >> /etc/modules-load.d/containerd.conf

  modprobe overlay
  modprobe br_netfilter

  echo "net.bridge.bridge-nf-call-iptables  = 1" > /etc/sysctl.d/99-kubernetes-cri.conf
  echo "net.ipv4.ip_forward                 = 1" >> /etc/sysctl.d/99-kubernetes-cri.conf
  echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/99-kubernetes-cri.conf

  sysctl --system

  rm -rf /etc/containerd/config.toml

  systemctl start containerd
  systemctl enable containerd

  echo "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd" > /etc/default/kubelet

  systemctl enable kubelet
}

function init-kubeadm-kubeconfig()
{
  if [[ ! -d "/etc/kubernetes" ]]
  then
    mkdir /etc/kubernetes
  fi
  echo -e "apiVersion: kubeadm.k8s.io/v1beta2" > /etc/kubernetes/kubeadm.yaml
  echo -e "kind: InitConfiguration" >> /etc/kubernetes/kubeadm.yaml
  echo -e "bootstrapTokens:" >> /etc/kubernetes/kubeadm.yaml
  echo -e "  - ttl: \"0\"" >> /etc/kubernetes/kubeadm.yaml
  if [[ $cnt_type = "containerd" ]]
  then
    echo -e "nodeRegistration:" >> /etc/kubernetes/kubeadm.yaml
    echo -e "  criSocket: /run/containerd/containerd.sock" >> /etc/kubernetes/kubeadm.yaml
  fi
  echo -e "---" >> /etc/kubernetes/kubeadm.yaml
  echo -e "apiVersion: kubeadm.k8s.io/v1beta2" >> /etc/kubernetes/kubeadm.yaml
  echo -e "kind: ClusterConfiguration" >> /etc/kubernetes/kubeadm.yaml
  if [[ -n $fip ]]
  then
  echo -e "controlPlaneEndpoint: \"$fip\"" >> /etc/kubernetes/kubeadm.yaml
  fi
  echo -e "networking:" >> /etc/kubernetes/kubeadm.yaml
  echo -e "  podSubnet: \"${kube_pod_subnet}\"" >> /etc/kubernetes/kubeadm.yaml
  echo -e "kubernetesVersion: \"v${kube_version}\"" >> /etc/kubernetes/kubeadm.yaml
  echo -e "imageRepository: \"${kube_image_server}\"" >> /etc/kubernetes/kubeadm.yaml
}


yamlUrl="https://gitee.com/syswu/yamls/raw/master/"
plugins="collector/list"
network="https://docs.projectcalico.org/archive/v3.19/manifests/calico.yaml"

function init-k8s-plugins()
{
   rm -rf /etc/kubernetes/kubeenv.list
   echo -e "$network" > /etc/kubernetes/kubeenv.list 
 
   array=(${plugins//,/ }) 
   for var in ${array[@]}
   do
     curl $yamlUrl$var > /tmp/list
     for line in `cat /tmp/list` 
     do 
       echo ${line} >> /etc/kubernetes/kubeenv.list
     done
   done
}

function init-env()
{
  if [[ -n $(cat /etc/os-release | grep centos) ]]
  then
    disable-centos-security
    add-yum-repository
    if [[ $cnt_type == "docker" ]]
    then
      yum-docker-k8s
    elif [[ $cnt_type == "containerd" ]]
    then
      yum-containerd-k8s
    else
      echo "only support docker and containerd"
      exit 1
    fi
  elif [[ -n $(cat /etc/os-release | grep ubuntu) ]]
  then
    disable-ubuntu-security
    add-apt-repository
    if [[ $cnt_type=="docker" ]]
    then
      apt-docker-k8s
    elif [[ $cnt_type=="containerd" ]]
    then
      apt-containerd-k8s
    else
      echo "only support docker and containerd"
      exit 1
    fi
  else
    echo "only support centos and ubuntu."
    exit 1
  fi
  init-kubeadm-kubeconfig
  init-k8s-plugins
}

###########################################################
##
##  init-kvm-env
##
##########################################################

function init-kvm-env()
{
  if [[ -n $(cat /etc/os-release | grep centos) ]]
  then
    disable-centos-security
    add-kvm-yum-repository
    yum install qemu-kvm libvirt libvirt-python virt-install virt-manager -y
  elif [[ -n $(cat /etc/os-release | grep ubuntu) ]]
  then
    disable-ubuntu-security
    add-kvm-apt-repository
    apt-get install qemu-kvm libvirt libvirt-python virt-install virt-manager -y
  else
    echo "only support centos and ubuntu."
    exit 1
  fi
  systemctl start libvirtd
  systemctl enable libvirtd
}

function add-kvm-yum-repository()
{
  yum install centos-release-openstack-$openstack lrzsz -y
}

function add-kvm-apt-repository
{
  add-apt-repository cloud-archive:$openstack
}

###########################################################
##
##  Experimental
##
##########################################################

function init-env-exp()
{
  init-env-disable-selinux
  init-env-disable-firewalld
  init-env-repository
  if [[ -z $2 ]]
  then
    init-containerd-software
  elif [[ $2 == "docker" ]]
  then
    init-docker-software
  elif [[ $2 == "containerd" ]]
  then
    init-containerd-software
  else
    echo "only support docker or containerd"
    exit 1
  fi
  init-env-kubeconfig
  init-env-kubecomp
}


###########################################################
##
##  init-kube
##
##########################################################

function init-kube()
{
  systemctl restart kubelet

  swapoff -a
  echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  echo "1" > /proc/sys/net/ipv4/ip_forward

  kubeadm init --config /etc/kubernetes/kubeadm.yaml

  rm -rf $HOME/.kube
  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
  iptables -P FORWARD ACCEPT

  while read line
  do
    kubectl apply -f $line
  done  < /etc/kubernetes/kubeenv.list

}

###########################################################
##
##  kube-backend
##
##########################################################

backendUrl="https://gitee.com/syswu/yamls/raw/master/backend"
tokenFile="kube-token.yaml"
databaseFile="kube-database-postgres.yaml"
messageFile="kube-message-rabbitmq.yaml"
mirrorFile="kube-runtime-mirror.yaml"
mapperFile="kube-api-mapper.yaml"
dir="/opt/yamls"
type="postgres"

function init-backend()
{
  mkdir -p $dir
  
  rm -rf /$dir/$tokenFile
  rm -rf /$dir/$databaseFile
  rm -rf /$dir/$messageFile
  rm -rf /$dir/$mirrorFile
  rm -rf /$dir/$mapperFile
  
  wget -P /$dir/$token $backendUrl/$tokenFile
  wget -P /$dir/$database $backendUrl/$databaseFile
  wget -P /$dir/$message $backendUrl/$messageFile
  wget -P /$dir/$mirror $backendUrl/$mirrorFile
  wget -P /$dir/$mapper $backendUrl/$mapperFile
  
  kubectl apply -f /$dir/$tokenFile
  kubectl apply -f /$dir/$databaseFile
  #kubectl apply -f /$dir/$messageFile
  
  while true
  do
    res=$(kubectl get po -A | grep -v Running | grep -v NAMESPACE)
    if [[ -z "$res" ]]
    then
      break
    fi
    sleep 5s
  done
  
  token=$(kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep kubernetes-client | awk '{print $1}') | grep "token:" | awk -F":" '{print$2}' | sed 's/ //g')


  ## arch
  arch=""

  if [[ $(arch) == "x86_64" ]]
  then
    arch="amd64"
  elif [[ $(arch) == "aarch64" ]]
  then
    arch="arm64"
  else
    echo "only support x86_64(amd64) and aarch64(arm64)"
    exit 1
  fi

  # host and url
  name=$(hostname | tr '[A-Z]' '[a-z]')
  host=$(kubectl get no $name -o yaml | grep "\- address:" | head -1 | awk -F":" '{print$2}' | sed  's/^[ \t]*//g')
  url="https:\/\/"$host":6443"

  #@ port
  port="30306"

  sed -i "s/#type#/$type/g" $dir/$mirrorFile
  sed -i "s/#host#/$host/g" $dir/$mirrorFile
  sed -i "s/#port#/$port/g" $dir/$mirrorFile
  sed -i "s/#url#/$url/g" $dir/$mirrorFile
  sed -i "s/#token#/$token/g" $dir/$mirrorFile
  sed -i "s/#version#/$kube_backend_version/g" $dir/$mirrorFile
  sed -i "s/#arch#/$arch/g" $dir/$mirrorFile

  sed -i "s/#type#/$type/g" $dir/$mapperFile
  sed -i "s/#host#/$host/g" $dir/$mapperFile
  sed -i "s/#port#/$port/g" $dir/$mapperFile
  sed -i "s/#url#/$url/g" $dir/$mapperFile
  sed -i "s/#token#/$token/g" $dir/$mapperFile
  sed -i "s/#version#/$kube_backend_version/g" $dir/$mapperFile
  sed -i "s/#arch#/$arch/g" $dir/$mapperFile

  kubectl apply -f $dir/$mirrorFile
  kubectl apply -f $dir/$mapperFile
}


###########################################################
##
##  kube-frontend
##
##########################################################

frontendUrl="https://gitee.com/syswu/yamls/raw/master/frontend"

function init-frontend()
{
   rm -rf /tmp/list
   wget -P /tmp/ $frontendUrl/list
   
   for name in `cat /tmp/list`
   do
     kubectl apply -f $name
   done
   
   rm -rf /tmp/user-admin.json
   wget -P /tmp/ $frontendUrl/users/user-admin.json
   token=$(kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep kubernetes-client | awk '{print $1}') | grep "token:" | awk -F":" '{print$2}' | sed 's/ //g')
   sed -i "s/#token#/$token/g" /tmp/user-admin.json
   kubectl apply -f /tmp/user-admin.json
}

###########################################################
##
##  help
##
##########################################################


function cmddesc()
{
  echo -e "Welcome to kubeinst ($VERSION), install Kubernetes-based systems from scratch.\n"
}


function help()
{
  cmddesc
  echo -e "Commands:"
  echo -e "  init-env       :\t(Init): simplify configuring node, such as disable selinux, install docker"
  echo -e "  init-kube      :\t(Init): deploy Kubernetes as your want by editing /etc/kubernetes/kubeenv.list. Now it includes calico, prometheus, grafna"
  echo -e "  init-backend   :\t(Init): install backend services, see project https://github.com/kubesys/kube-backend"
  echo -e "  init-frontend  :\t(Init): install Kuberetes-based dashboard, see project https://github.com/kubesys/kube-frontend"
  echo -e "  init-kvm-env   :\t(Init): install kvm and libvirt"
}


case $1 in
  "init-env")
    init-env $*
    ;;
  "init-kube")
    init-kube $*
    ;;
  "init-backend")
    init-backend $*
    ;;
  "init-frontend")
    init-frontend $*
    ;;
  "init-kvm-env")
    init-kvm-env $*
    ;;
  "--help")
    help
    ;;
  *)
  help
  ;;
esac
